version: '3.9'
services:

  db:
    image: postgres:17.0-alpine
    volumes:
      - "db_data:/var/lib/postgresql/data"
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER_FILE: /run/secrets/psql_db_username
      POSTGRES_PASSWORD_FILE: /run/secrets/psql_db_password
      POSTGRES_DATABASE_FILE: /run/secrets/psql_db_database
    secrets:
      - psql_db_password
      - psql_db_username
      - psql_db_database
    shm_size: 256M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "bhs"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s  
    restart: always
    security_opt:
      - no-new-privileges
    labels:
      - service_type=database
  
  web_app:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile.yaml
      context: ./app
    environment:
      POSTGRES_USER_FILE: /run/secrets/psql_db_username
      POSTGRES_PASSWORD_FILE: /run/secrets/psql_db_password
      POSTGRES_DATABASE_FILE: /run/secrets/psql_db_database
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      APP_PORT: 8080
    secrets:
      - psql_db_password
      - psql_db_username
      - psql_db_database
    ports:
      - '8080:8080'
    restart: always
    security_opt:
      - no-new-privileges
    labels:
      - service_type=webserver

secrets:
  psql_db_password:
    file: ./db/db_password.txt
  psql_db_username:
    file: ./db/db_username.txt
  psql_db_database:
    file: ./db/db_database.txt
  
volumes:
  db_data:
    driver: local