FROM golang:1.22.8-alpine as builder
WORKDIR /app
COPY . .
RUN go mod init app
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -o app

FROM scratch
WORKDIR /app
COPY --from=builder /app .
CMD ["./app"]
