---
- hosts: all 
  roles:
    - role: firewall
    - role: chrony
    - role: docker

  pre_tasks:
    - name: Install docker requirments
      ansible.builtin.pip:
        name:
          - "docker==6.1.3"
          - "requests<2.32"
          - "docker-compose>2.18.0"
      tags: [web, prod, db, infra, dev]

  tasks:
    - name: Copy all infra data on remote hostn
      ansible.builtin.copy:
        src: "{{ source_code_path }}"
        dest: "{{ docker_compose_path }}"
      tags: [web, prod, db, infra, dev]

    - name: Deploy only infrastracture
      community.docker.docker_compose_v2:
        project_src: "{{ docker_compose_path }}"
        state: absent
        services: db
        recreate: always
      tags: [infra, db, dev]
    
    - name: Deploy app
      community.docker.docker_compose_v2:
        project_src: "{{ docker_compose_path }}"
        state: absent
        recreate: always
      tags: [web, prod, db, infra, dev]